name: 'Deploy review apps to gh-pages'
description: |
  Automatically deploy static apps to gh-pages, so you're able to easily QA it
inputs:
  gh-pages-source-branch:  # id of input
    description: 'The branch you configured in github to be the source for gh-pages. defaults to "gh-pages run"'
    default: 'gh-pages'
  public-assets-dir:  # id of input
    description: 'The directory where you build artifacts will live'
    default: 'dist'
  output-dir:
    description: |
      'Dir is related to URL path in github pages.
      If you want something like: https://githubname.github.io/repo/storybooks/branch-name, pass string "storybook"'
    default: 'review-apps'
runs:
  using: 'node12'
  main: 'dist/index.js'