name: 'Deploy review apps to gh-pages'
description: |
  Automatically deploy static apps to gh-pages, so you're able to easily QA it
inputs:
  gh-pages-source-branch:  # id of input
    description: 'The branch you configured in github to be the source for gh-pages. defaults to "gh-pages run"'
    default: 'gh-pages'
  public-assets-dir:  # id of input
    description: 'The directory where you build artifacts will live'
    default: 'dist'
  output-dir:
    description: |
      'Dir is related to URL path in github pages.
      If you want something like: https://githubname.github.io/repo/storybooks/branch-name, pass string "storybook"'
    default: 'review-apps'
runs:
  using: "composite"
  steps:
    - name: 'Configure git author'
      run: |
        git config --global user.name ${{github.event.pusher.name}}
        git config --global user.email ${{github.event.pusher.email}}
        git config pull.rebase true
      shell: bash
    - name: 'Commit udpated review app'
      run: |
        BRANCH_NAME=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
        mv ${{inputs.public-assets-dir}} .tmp
        git checkout ${{inputs.gh-pages-source-branch}}
        rm -r ${{inputs.public-assets-dir}}/$BRANCH_NAME
        mv .tmp ${{inputs.public-assets-dir}}/$BRANCH_NAME
        git status | grep ${{inputs.output-dir}}
        if [ #? -eq 0 ]; then
          git add ${{inputs.output-dir}}/$BRANCH_NAME
          git commit -m "[skip ci]  ref to ${{github.event.head_commit.id}}"
        fi
      shell: bash
    - name: 'Try to push with updated review app'
      run: |
        counter=0
        function retry() {
          echo "Retry to push until succeeds, just in case there another push just happened"
          git pull origin ${{inputs.gh-pages-source-branch}}
          git push origin ${{inputs.gh-pages-source-branch}}
          if [ $? -eq 0 ]; then
            if [ $counter -lt 5 ]; then
              retry
              ((counter=counter+1))
            fi
          fi
        }
        retry
      shell: bash
