name: 'Build and deploy create react app to review apps, so you can safely QA it'
on: push
jobs:
  stories:
    runs-on: ubuntu-latest
    name: Manage review apps
    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v1-
      - name: Install deps checking cache hit
        run: yarn install --frozen-lockfile

      # This is how you'll use the action
      - name: Replace with next line with - 'sauloxd/review-apps@X.X.X'
        uses: ./ # Replace here with sauloxd/review-apps@X.X.X
        with:
          build-cmd: 'yarn run cra:build'
          branch: 'review-apps'
          dist: 'packages/cra-example/build'
          slug: 'cra'
          public-url: true

      # This is how you'll use the action
      - name: Replace with next line with - 'sauloxd/review-apps@X.X.X'
        uses: ./ # Replace here with sauloxd/review-apps@X.X.X
        with:
          build-cmd: 'yarn run cra:storybook'
          branch: 'review-apps'
          dist: 'packages/cra-example/storybook-static'
          slug: 'cra-sb'
          public-url: true

      # This is how you'll use the action
      - name: Replace with next line with - 'sauloxd/review-apps@X.X.X'
        uses: ./ # Replace here with sauloxd/review-apps@X.X.X
        with:
          build-cmd: 'yarn run cra:storybook'
          branch: 'review-apps'
          dist: 'packages/gatsby/public'
          slug: 'gatsby'
          public-url: true